In [188]:
import pandas as pd
from pandas_datareader import data
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mp
import datetime as dt

In [172]:
#Operate on original data file
#use Pandas & dataframe to trim, drop columns that are of no use
filename = "/Users/Sirius/Downloads/yellow_tripdata_2015-06.csv"
data = pd.read_csv(filename)
data_df = pd.DataFrame(data)
data_df.drop(data_df.columns[[0,7,8,11,12,13,14,15,16,17]],axis = 1, inplace = True)
print(data_df)

         tpep_pickup_datetime tpep_dropoff_datetime  passenger_count  \
0         2015-06-02 11:19:29   2015-06-02 11:47:52                1
1         2015-06-02 11:19:30   2015-06-02 11:27:56                1
2         2015-06-02 11:19:31   2015-06-02 11:30:30                1
3         2015-06-02 11:19:31   2015-06-02 11:39:02                1
4         2015-06-02 11:19:32   2015-06-02 11:32:49                1
5         2015-06-02 11:19:33   2015-06-02 11:28:48                1
6         2015-06-02 11:19:34   2015-06-02 11:38:46                1
7         2015-06-02 11:19:35   2015-06-02 12:36:46                4
8         2015-06-02 11:19:36   2015-06-02 11:45:19                1
9         2015-06-02 11:19:38   2015-06-02 11:23:50                1
10        2015-06-02 11:19:38   2015-06-02 11:19:43                3
11        2015-06-02 11:19:39   2015-06-02 11:36:43                1
12        2015-06-02 11:19:40   2015-06-02 11:34:34                1
13        2015-06-02 11:19:41   2015-06-02 11:23:56                2
14        2015-06-02 11:19:41   2015-06-02 11:29:59                1
15        2015-06-02 11:19:42   2015-06-02 11:22:33                2
16        2015-06-02 11:19:44   2015-06-02 11:38:10                1
17        2015-06-02 11:19:44   2015-06-02 11:30:31                1
18        2015-06-02 11:19:45   2015-06-02 11:42:03                1
19        2015-06-02 11:19:47   2015-06-02 11:26:48                1
20        2015-06-02 11:19:48   2015-06-02 11:34:36                1
21        2015-06-02 11:19:49   2015-06-02 11:33:45                1
22        2015-06-02 11:19:50   2015-06-02 11:38:54                1
23        2015-06-02 11:19:51   2015-06-02 11:33:13                1
24        2015-06-02 11:19:52   2015-06-02 11:53:51                1
25        2015-06-02 11:19:53   2015-06-02 11:30:16                1
26        2015-06-02 11:19:54   2015-06-02 11:29:50                1
27        2015-06-02 11:19:54   2015-06-02 11:27:46                5
28        2015-06-02 11:19:55   2015-06-02 11:34:39                2
29        2015-06-02 11:19:56   2015-06-02 11:32:24                1
...                       ...                   ...              ...
12324905  2015-06-30 21:54:03   2015-06-30 22:08:21                1
12324906  2015-06-30 21:54:03   2015-06-30 22:13:20                1
12324907  2015-06-30 21:54:04   2015-06-30 21:59:17                2
12324908  2015-06-30 21:54:05   2015-06-30 22:15:41                1
12324909  2015-06-30 21:54:05   2015-06-30 22:15:18                1
12324910  2015-06-30 21:54:01   2015-06-30 22:12:45                2
12324911  2015-06-30 21:54:07   2015-06-30 22:08:48                1
12324912  2015-06-30 21:54:07   2015-06-30 22:03:21                1
12324913  2015-06-30 21:54:08   2015-06-30 22:02:24                1
12324914  2015-06-30 21:54:08   2015-06-30 21:58:48                5
12324915  2015-06-30 21:54:09   2015-06-30 22:11:14                1
12324916  2015-06-30 21:54:09   2015-06-30 22:10:59                2
12324917  2015-06-30 21:54:10   2015-06-30 22:05:28                6
12324918  2015-06-30 21:54:11   2015-06-30 22:01:14                1
12324919  2015-06-30 21:54:12   2015-06-30 22:12:44                6
12324920  2015-06-30 21:54:13   2015-06-30 22:07:24                1
12324921  2015-06-30 21:54:14   2015-06-30 22:01:59                1
12324922  2015-06-30 21:54:14   2015-06-30 21:59:18                4
12324923  2015-06-30 21:54:15   2015-06-30 22:11:22                1
12324924  2015-06-30 21:54:15   2015-06-30 22:06:34                1
12324925  2015-06-30 21:54:16   2015-06-30 22:05:47                1
12324926  2015-06-30 21:54:17   2015-06-30 22:35:30                1
12324927  2015-06-30 21:54:18   2015-06-30 22:11:42                2
12324928  2015-06-30 21:54:18   2015-06-30 22:07:42                1
12324929  2015-06-30 21:54:19   2015-06-30 22:09:03                1
12324930  2015-06-30 21:54:20   2015-06-30 22:08:54                1
12324931  2015-06-30 21:54:20   2015-06-30 22:16:23                1
12324932  2015-06-30 21:54:21   2015-06-30 22:04:12                6
12324933  2015-06-30 21:54:21   2015-06-30 22:09:35                1
12324934  2015-06-30 21:54:22   2015-06-30 22:02:42                1

          trip_distance  pickup_longitude  pickup_latitude  dropoff_longitude  \
0                  1.63        -73.954430        40.764141         -73.974754
1                  0.46        -73.971443        40.758942         -73.978539
2                  0.87        -73.978111        40.738434         -73.990273
3                  2.13        -73.945892        40.773529         -73.971527
4                  1.40        -73.979088        40.776772         -73.982162
5                  1.40        -73.944641        40.779465         -73.961365
6                  1.80        -73.992867        40.748211         -73.969772
7                 11.90        -73.863075        40.769253         -73.986710
8                  1.27        -73.991432        40.749306         -73.985062
9                  0.60        -73.970734        40.796207         -73.977470
10                 0.01          0.000000         0.000000           0.000000
11                 1.65        -73.980492        40.730690         -73.996017
12                 1.14        -73.950104        40.777283         -73.954102
13                 0.50        -73.954803        40.765667         -73.962517
14                 1.28        -73.992508        40.728512         -73.995743
15                 0.60        -73.971939        40.781902         -73.978149
16                 1.41        -73.972748        40.744553         -73.963066
17                 0.70        -73.958519        40.781433         -73.959229
18                 1.90        -74.007637        40.731834         -73.990746
19                 1.10        -73.955643        40.776382         -73.960464
20                 3.90        -73.949623        40.772671         -73.987640
21                 1.99        -73.982269        40.773991         -73.959869
22                 1.94        -73.984970        40.744328         -73.967270
23                 1.10        -73.964371        40.769894         -73.975189
24                 3.80        -73.960022        40.773380         -74.000427
25                 1.20        -74.005524        40.715153         -74.015137
26                 0.94        -73.990471        40.751163         -73.986069
27                 1.35        -73.983185        40.750263         -73.999237
28                 1.90        -73.990143        40.740814         -74.005508
29                 1.30        -73.994301        40.751057         -73.979904
...                 ...               ...              ...                ...
12324905           1.81        -73.993507        40.741962         -73.980652
12324906           2.53        -74.006363        40.739471         -73.979156
12324907           1.36        -73.938049        40.796696         -73.946190
12324908           8.60        -73.871002        40.773827         -73.973831
12324909           4.70        -74.006577        40.744816         -73.965668
12324910           5.97        -74.004227        40.747482         -73.931137
12324911           3.00        -73.955383        40.779568         -73.987106
12324912           0.95        -73.998016        40.737888         -73.982758
12324913           1.70          0.000000         0.000000           0.000000
12324914           1.05        -73.991890        40.750622         -74.003311
12324915           2.90        -73.952904        40.783230         -73.978294
12324916           3.70        -74.005325        40.721786         -73.982323
12324917           3.27        -74.003426        40.750668         -74.016106
12324918           1.70        -73.951134        40.778713         -73.962799
12324919           2.82        -73.971008        40.751438         -74.005409
12324920           2.39        -73.955811        40.772121         -73.979210
12324921           1.62        -73.971443        40.757721         -73.956642
12324922           1.93        -73.966057        40.762070         -73.950706
12324923           4.96        -73.939835        40.707626         -73.974800
12324924           1.50        -73.992661        40.763371         -73.992661
12324925           2.93        -73.970139        40.756512         -73.956612
12324926          19.40        -73.782440        40.644489         -73.979294
12324927           3.50        -73.991806        40.759697         -73.981239
12324928           1.63        -73.971306        40.757690         -73.991325
12324929           3.50          0.000000         0.000000           0.000000
12324930           1.90        -73.924347        40.774315         -73.919617
12324931           3.10        -73.951843        40.773781         -73.991394
12324932           1.55        -73.961060        40.813545         -73.945053
12324933           3.20        -73.984375        40.761627         -74.002548
12324934           1.40        -74.002777        40.739452         -73.987648

          dropoff_latitude  total_amount
0                40.754093         17.80
1                40.761909          8.30
2                40.745438         11.00
3                40.760330         17.16
4                40.758999         10.30
5                40.771561         10.55
6                40.748459         16.30
7                40.761307         73.84
8                40.759525         15.80
9                40.789509          6.30
10                0.000000         52.80
11               40.716331         14.80
12               40.763763         11.30
13               40.768044          6.60
14               40.740971          8.80
15               40.777328          4.80
16               40.761719         15.36
17               40.774303          8.80
18               40.752304         19.12
19               40.765522          7.30
20               40.735611         19.55
21               40.775372         14.12
22               40.769188         13.30
23               40.756977         12.36
24               40.737537         26.75
25               40.709240         10.55
26               40.742367          8.80
27               40.742435          8.80
28               40.723015         11.80
29               40.761692         10.30
...                    ...           ...
12324905         40.764545         14.76
12324906         40.760399         15.30
12324907         40.780853          8.76
12324908         40.749996         28.30
12324909         40.712852         23.76
12324910         40.764900         24.96
12324911         40.749710         14.30
12324912         40.731483          8.80
12324913          0.000000         11.16
12324914         40.742554          6.80
12324915         40.746017         16.45
12324916         40.768353         19.55
12324917         40.708817         15.96
12324918         40.794086         11.00
12324919         40.735939         18.36
12324920         40.747101         14.30
12324921         40.771523         11.16
12324922         40.785900          9.80
12324923         40.680370         18.80
12324924         40.763371         10.80
12324925         40.747921         16.64
12324926         40.642612         56.30
12324927         40.725273         18.95
12324928         40.750286         13.50
12324929          0.000000         18.50
12324930         40.755508         12.80
12324931         40.759972         17.80
12324932         40.808304          9.80
12324933         40.730511         13.80
12324934         40.745705         10.55

[12324935 rows x 9 columns]

In [14]:
type(data_df)

pandas.core.frame.DataFrame

In [15]:
data_df['pickup_longitude'][1]

-73.999369000000002

In [16]:
len(data_df['pickup_longitude'])

15097861

In [3]:
#set latitude & longitude's up & bottom boundaries for three different firms
citi_la_b = 40.758406  
citi_la_u = 40.759645   
citi_lo_u = -73.971069  
citi_lo_b = -73.972052  
gs_la_b = 40.7139
gs_la_u = 40.7159
gs_lo_b = -74.0153
gs_lo_u = -74.0133
jp_la_b = 40.755370
jp_la_u = 40.756599
jp_lo_b = -73.976487
jp_lo_u = -73.975410

In [173]:
#filter with boundaries
temp_g = data_df[(data_df['pickup_longitude'] >= -74.0153) & (data_df['pickup_longitude'] <= -74.0133)]
temp_g = temp_g[(temp_g['pickup_latitude'] >= 40.7139) & (temp_g['pickup_latitude'] <= 40.7159)]
len(temp_g)

22329

In [174]:
#filter with boundaries
temp_c = data_df[(data_df['pickup_longitude'] >= citi_lo_b) & (data_df['pickup_longitude'] <= citi_lo_u)]
temp_c = temp_c[(temp_c['pickup_latitude'] >= citi_la_b) & (temp_c['pickup_latitude'] <= citi_la_u)]
len(temp_c)

5654

In [175]:
#filter with boundaries
temp_j = data_df[(data_df['pickup_longitude'] >= jp_lo_b) & (data_df['pickup_longitude'] <= jp_lo_u)]
temp_j = temp_j[(temp_j['pickup_latitude'] >= jp_la_b) & (temp_j['pickup_latitude'] <= jp_la_u)]
len(temp_j)

10316

In [7]:
#tempg_1 = temp_g
#tempc_1 = temp_c
#tempj_1 = temp_j

In [187]:
#tempx_1 is the final list of everything, since the final data was generated using multiple separate files
tempg_1 = tempg_1.append(temp_g,ignore_index=True)
tempc_1 = tempc_1.append(temp_c,ignore_index=True)
tempj_1 = tempj_1.append(temp_j,ignore_index=True)
temp_g['passenger_count'][167] = 2

/Users/Sirius/anaconda/lib/python3.4/site-packages/ipykernel/__main__.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,total_amount
167,2015-06-02 11:21:38,2015-06-02 11:48:10,2,7.30,-73.975792,40.760117,-74.013786,40.714672,32.15
467,2015-06-02 11:19:39,2015-06-02 11:32:05,1,1.10,-74.017288,40.705364,-74.014923,40.714180,9.80
592,2015-06-02 11:20:16,2015-06-02 11:47:50,1,3.32,-73.994133,40.751259,-74.013687,40.714886,19.80
814,2015-06-02 11:21:09,2015-06-02 11:42:27,1,2.72,-74.004990,40.751682,-74.014641,40.714306,18.17
1051,2015-06-02 11:22:12,2015-06-02 12:15:44,1,6.10,-73.971123,40.782951,-74.013687,40.715080,39.96
1094,2015-06-02 11:19:55,2015-06-02 11:24:44,3,0.42,-74.007118,40.713055,-74.013405,40.715836,7.25
1288,2015-06-02 11:20:54,2015-06-02 12:14:31,1,6.70,-73.973289,40.795246,-74.013367,40.715130,35.30
1348,2015-06-02 11:23:08,2015-06-02 12:18:46,1,6.00,-73.966209,40.767609,-74.013878,40.714729,39.44
1488,2015-06-02 11:23:28,2015-06-02 11:34:55,5,1.37,-74.007088,40.706131,-74.013924,40.713959,12.25
1943,2015-06-02 11:29:17,2015-06-02 11:56:58,1,3.40,-73.994469,40.750935,-74.014801,40.713936,23.15
2143,2015-06-02 11:31:54,2015-06-02 12:20:20,1,5.70,-73.978554,40.783272,-74.013420,40.715733,34.84
2570,2015-06-02 11:31:01,2015-06-02 11:58:40,1,6.50,-73.972687,40.758724,-74.013718,40.714775,27.30
3089,2015-06-02 11:26:59,2015-06-02 11:36:22,5,1.11,-74.017174,40.705276,-74.015015,40.714046,9.96
3168,2015-06-02 11:27:03,2015-06-02 11:49:32,2,7.97,-73.968910,40.763855,-74.014015,40.714668,32.76
3178,2015-06-02 11:27:11,2015-06-02 11:54:08,3,7.03,-73.974808,40.757320,-74.013969,40.714817,32.16
3630,2015-06-02 11:28:03,2015-06-02 11:38:38,1,1.10,-73.999886,40.720406,-74.013710,40.714981,11.00
3644,2015-06-02 11:28:13,2015-06-02 11:42:36,1,4.77,-73.975418,40.728748,-74.014359,40.714840,21.96
3969,2015-06-02 11:32:26,2015-06-02 12:16:19,1,4.30,-73.984810,40.757748,-74.013992,40.713902,27.80
4900,2015-06-02 11:33:33,2015-06-02 11:40:27,1,0.90,-74.017288,40.705357,-74.013847,40.714035,7.30
5218,2015-06-04 15:16:17,2015-06-04 15:33:00,1,2.90,-73.986984,40.745190,-74.013603,40.715328,17.16
6614,2015-06-04 15:20:39,2015-06-04 15:29:17,1,1.40,-74.008354,40.733990,-74.015099,40.715527,10.55
6711,2015-06-04 15:20:53,2015-06-04 15:45:13,1,5.11,-73.977531,40.764030,-74.013641,40.714779,24.80
6830,2015-06-04 15:21:29,2015-06-04 15:37:31,1,2.95,-73.989777,40.741692,-74.013962,40.714268,15.96
10995,2015-06-02 11:34:21,2015-06-02 12:16:00,2,4.20,-73.990173,40.756882,-74.014008,40.713913,26.80
11533,2015-06-02 11:36:21,2015-06-02 12:02:10,1,3.50,-73.993027,40.747898,-74.014893,40.714035,18.80
11694,2015-06-02 11:36:56,2015-06-02 12:25:13,1,4.90,-73.981506,40.759457,-74.014465,40.715427,37.25
11771,2015-06-02 11:36:56,2015-06-02 12:13:53,1,7.49,-73.978264,40.762497,-74.014267,40.714008,39.12
11833,2015-06-02 11:37:16,2015-06-02 12:05:19,1,3.90,-73.980103,40.754543,-74.014076,40.714783,24.35
12205,2015-06-04 15:23:56,2015-06-04 15:55:15,1,6.90,-73.965942,40.757816,-74.014076,40.713997,29.80
12714,2015-06-04 15:25:53,2015-06-04 15:40:01,1,1.30,-74.005417,40.728115,-74.014236,40.714417,13.50
...,...,...,...,...,...,...,...,...,...
12277416,2015-06-30 21:20:17,2015-06-30 21:33:33,1,2.05,-73.990448,40.718933,-74.015091,40.715786,14.16
12277774,2015-06-30 21:19:39,2015-06-30 21:39:46,1,4.50,-73.987686,40.760578,-74.014565,40.715675,19.30
12278027,2015-06-30 21:21:42,2015-06-30 21:37:03,2,2.79,-74.011612,40.714249,-74.014267,40.715439,13.30
12278887,2015-06-30 21:20:11,2015-06-30 22:00:25,2,5.90,-73.984200,40.762543,-74.014732,40.714413,32.76
12279480,2015-06-30 21:24:45,2015-06-30 21:42:26,3,4.30,-73.988075,40.756458,-74.014755,40.714199,17.80
12280293,2015-06-30 21:28:30,2015-06-30 21:36:43,2,1.05,-74.002533,40.708698,-74.014572,40.715439,9.96
12280460,2015-06-30 21:23:54,2015-06-30 21:31:54,1,1.77,-73.999306,40.730057,-74.014587,40.715096,11.76
12280572,2015-06-30 21:29:44,2015-06-30 21:43:39,1,4.35,-73.990250,40.718887,-74.015236,40.714100,20.16
12283013,2015-06-30 21:27:37,2015-06-30 21:34:37,1,1.60,-74.003250,40.726986,-74.014931,40.714001,10.55
12283026,2015-06-30 21:27:43,2015-06-30 21:49:25,1,5.30,-73.976776,40.780037,-74.014343,40.715588,21.30
12285140,2015-06-30 22:11:14,2015-06-30 22:21:25,5,2.49,-74.003014,40.744267,-74.015045,40.715660,13.30
12287913,2015-06-30 21:32:00,2015-06-30 21:40:18,1,1.40,-74.004570,40.730618,-74.014893,40.715748,10.30
12288558,2015-06-30 21:50:02,2015-06-30 21:56:23,1,1.45,-74.007660,40.704941,-74.014374,40.715649,9.96
12288696,2015-06-30 22:23:58,2015-06-30 22:41:26,5,3.91,-73.996056,40.759136,-74.015282,40.715649,17.80
12290211,2015-06-30 22:12:54,2015-06-30 22:17:05,2,1.48,-74.004318,40.730824,-74.014999,40.715755,8.76
12291974,2015-06-30 22:26:05,2015-06-30 22:52:15,1,4.91,-73.977386,40.759022,-74.015068,40.715111,21.30
12292263,2015-06-30 22:17:46,2015-06-30 22:25:45,1,1.20,-74.004822,40.721058,-74.014458,40.715416,8.80
12294119,2015-06-30 22:41:37,2015-06-30 22:56:45,1,2.65,-73.985229,40.739014,-74.014519,40.715565,15.96
12295130,2015-06-30 22:43:27,2015-06-30 22:52:02,2,1.58,-74.003479,40.733509,-74.013962,40.715420,11.76
12297626,2015-06-30 22:53:13,2015-06-30 23:04:54,1,2.19,-73.990852,40.734516,-74.014961,40.715595,13.30
12303128,2015-06-30 23:25:49,2015-06-30 23:37:06,5,1.49,-74.004410,40.721638,-74.014526,40.715443,12.10
12303777,2015-06-30 23:34:12,2015-06-30 23:48:43,1,3.11,-73.995064,40.744797,-74.013710,40.714951,16.80
12303819,2015-06-30 20:48:44,2015-06-30 21:16:35,1,7.31,-73.954559,40.763981,-74.013382,40.715092,31.30
12307600,2015-06-30 23:16:11,2015-06-30 23:30:23,1,6.66,-73.967407,40.756222,-74.015121,40.715626,26.16
12309168,2015-06-30 23:21:14,2015-06-30 23:41:38,1,7.15,-73.968895,40.754269,-74.014679,40.715508,29.16
12310170,2015-06-30 23:26:26,2015-06-30 23:38:43,1,2.40,-74.003799,40.742046,-74.014557,40.715408,14.15
12313350,2015-06-30 22:37:20,2015-06-30 23:03:42,1,5.00,-73.980087,40.754871,-74.013779,40.715267,25.07
12319899,2015-06-30 23:39:48,2015-07-01 00:00:43,1,4.56,-73.983261,40.761951,-74.015213,40.715771,24.12
12319984,2015-06-30 23:45:08,2015-06-30 23:51:47,1,1.51,-74.008286,40.705811,-74.014503,40.715393,9.96
12321935,2015-06-30 23:53:20,2015-07-01 00:13:09,1,4.80,-73.979340,40.752525,-74.015259,40.715801,23.15

In [ ]:
#these codes below are just like the above, different requirments

In [177]:
temp_g = data_df[(data_df['dropoff_longitude'] >= -74.0153) & (data_df['dropoff_longitude'] <= -74.0133)]
temp_g = temp_g[(temp_g['dropoff_latitude'] >= 40.7139) & (temp_g['dropoff_latitude'] <= 40.7159)]
len(temp_g)

38543

In [178]:
temp_c = data_df[(data_df['dropoff_longitude'] >= citi_lo_b) & (data_df['dropoff_longitude'] <= citi_lo_u)]
temp_c = temp_c[(temp_c['dropoff_latitude'] >= citi_la_b) & (temp_c['dropoff_latitude'] <= citi_la_u)]
len(temp_c)

7426

In [179]:
temp_j = data_df[(data_df['dropoff_longitude'] >= jp_lo_b) & (data_df['dropoff_longitude'] <= jp_lo_u)]
temp_j = temp_j[(temp_j['dropoff_latitude'] >= jp_la_b) & (temp_j['dropoff_latitude'] <= jp_la_u)]
len(temp_j)

11112

In [11]:
#tempg_2 = temp_g
#tempc_2 = temp_c
#tempj_2 = temp_j

In [180]:
tempg_2 = tempg_2.append(temp_g,ignore_index=True)
tempc_2 = tempc_2.append(temp_c,ignore_index=True)
tempj_2 = tempj_2.append(temp_j,ignore_index=True)

In [181]:
#save to csv files
name = "tempg_1.csv"
tempg_1.to_csv(name)
name = "tempg_2.csv"
tempg_2.to_csv(name)
name = "tempc_1.csv"
tempc_1.to_csv(name)
name = "tempc_2.csv"
tempc_2.to_csv(name)
name = "tempj_1.csv"
tempj_1.to_csv(name)
name = "tempj_2.csv"
tempj_2.to_csv(name)

In [ ]:
tempg_1

In [ ]:
temp_g_time = list()
#temp['tpep_pickup_datetime']
for y in temp_g['pickup_datetime']:
    temp_g_time.append(y)
#x = str(temp['tpep_pickup_datetime'][1])
temp_g_time_d = []
temp_g_time_t = []
temp_g_time[0][0:10]
temp_g_time[0][11:]
for x in temp_g_time:
    temp_g_time_d.append(x[0:10])
    temp_g_time_t.append(x[11:])
temp_g_time_d
len(temp_g_time_t)

In [ ]:
temp_c_time = list()
#temp['tpep_pickup_datetime']
for y in temp_c['pickup_datetime']:
    temp_c_time.append(y)
#x = str(temp['tpep_pickup_datetime'][1])
temp_c_time_d = []
temp_c_time_t = []
temp_c_time[0][0:10]
temp_c_time[0][11:]
for x in temp_c_time:
    temp_c_time_d.append(x[0:10])
    temp_c_time_t.append(x[11:])
temp_c_time_d
len(temp_c_time_t)

In [ ]:
temp_j_time = list()
#temp['tpep_pickup_datetime']
for y in temp_j['pickup_datetime']:
    temp_j_time.append(y)
#x = str(temp['tpep_pickup_datetime'][1])
temp_j_time_d = []
temp_j_time_t = []
temp_j_time[0][0:10]
temp_j_time[0][11:]
for x in temp_j_time:
    temp_j_time_d.append(x[0:10])
    temp_j_time_t.append(x[11:])
temp_j_time_d
len(temp_j_time_t)

In [ ]:
temp_g_time_t

In [ ]:
name = "2011_03_gs.csv"
temp_g.to_csv(name)

In [ ]:
name = "2011_03_citi.csv"
temp_c.to_csv(name)

In [ ]:
name = "2011_03_jp.csv"
temp_j.to_csv(name)

In [ ]:
filename = "/Users/Sirius/tempg_1.csv"
data1 = pd.read_csv(filename)
data1 = pd.DataFrame(data1)
print(data1)

In [190]:
temp_g

,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,total_amount
167,2015-06-02 11:21:38,2015-06-02 11:48:10,2,7.30,-73.975792,40.760117,-74.013786,40.714672,32.15
467,2015-06-02 11:19:39,2015-06-02 11:32:05,1,1.10,-74.017288,40.705364,-74.014923,40.714180,9.80
592,2015-06-02 11:20:16,2015-06-02 11:47:50,1,3.32,-73.994133,40.751259,-74.013687,40.714886,19.80
814,2015-06-02 11:21:09,2015-06-02 11:42:27,1,2.72,-74.004990,40.751682,-74.014641,40.714306,18.17
1051,2015-06-02 11:22:12,2015-06-02 12:15:44,1,6.10,-73.971123,40.782951,-74.013687,40.715080,39.96
1094,2015-06-02 11:19:55,2015-06-02 11:24:44,3,0.42,-74.007118,40.713055,-74.013405,40.715836,7.25
1288,2015-06-02 11:20:54,2015-06-02 12:14:31,1,6.70,-73.973289,40.795246,-74.013367,40.715130,35.30
1348,2015-06-02 11:23:08,2015-06-02 12:18:46,1,6.00,-73.966209,40.767609,-74.013878,40.714729,39.44
1488,2015-06-02 11:23:28,2015-06-02 11:34:55,5,1.37,-74.007088,40.706131,-74.013924,40.713959,12.25
1943,2015-06-02 11:29:17,2015-06-02 11:56:58,1,3.40,-73.994469,40.750935,-74.014801,40.713936,23.15
2143,2015-06-02 11:31:54,2015-06-02 12:20:20,1,5.70,-73.978554,40.783272,-74.013420,40.715733,34.84
2570,2015-06-02 11:31:01,2015-06-02 11:58:40,1,6.50,-73.972687,40.758724,-74.013718,40.714775,27.30
3089,2015-06-02 11:26:59,2015-06-02 11:36:22,5,1.11,-74.017174,40.705276,-74.015015,40.714046,9.96
3168,2015-06-02 11:27:03,2015-06-02 11:49:32,2,7.97,-73.968910,40.763855,-74.014015,40.714668,32.76
3178,2015-06-02 11:27:11,2015-06-02 11:54:08,3,7.03,-73.974808,40.757320,-74.013969,40.714817,32.16
3630,2015-06-02 11:28:03,2015-06-02 11:38:38,1,1.10,-73.999886,40.720406,-74.013710,40.714981,11.00
3644,2015-06-02 11:28:13,2015-06-02 11:42:36,1,4.77,-73.975418,40.728748,-74.014359,40.714840,21.96
3969,2015-06-02 11:32:26,2015-06-02 12:16:19,1,4.30,-73.984810,40.757748,-74.013992,40.713902,27.80
4900,2015-06-02 11:33:33,2015-06-02 11:40:27,1,0.90,-74.017288,40.705357,-74.013847,40.714035,7.30
5218,2015-06-04 15:16:17,2015-06-04 15:33:00,1,2.90,-73.986984,40.745190,-74.013603,40.715328,17.16
6614,2015-06-04 15:20:39,2015-06-04 15:29:17,1,1.40,-74.008354,40.733990,-74.015099,40.715527,10.55
6711,2015-06-04 15:20:53,2015-06-04 15:45:13,1,5.11,-73.977531,40.764030,-74.013641,40.714779,24.80
6830,2015-06-04 15:21:29,2015-06-04 15:37:31,1,2.95,-73.989777,40.741692,-74.013962,40.714268,15.96
10995,2015-06-02 11:34:21,2015-06-02 12:16:00,2,4.20,-73.990173,40.756882,-74.014008,40.713913,26.80
11533,2015-06-02 11:36:21,2015-06-02 12:02:10,1,3.50,-73.993027,40.747898,-74.014893,40.714035,18.80
11694,2015-06-02 11:36:56,2015-06-02 12:25:13,1,4.90,-73.981506,40.759457,-74.014465,40.715427,37.25
11771,2015-06-02 11:36:56,2015-06-02 12:13:53,1,7.49,-73.978264,40.762497,-74.014267,40.714008,39.12
11833,2015-06-02 11:37:16,2015-06-02 12:05:19,1,3.90,-73.980103,40.754543,-74.014076,40.714783,24.35
12205,2015-06-04 15:23:56,2015-06-04 15:55:15,1,6.90,-73.965942,40.757816,-74.014076,40.713997,29.80
12714,2015-06-04 15:25:53,2015-06-04 15:40:01,1,1.30,-74.005417,40.728115,-74.014236,40.714417,13.50
...,...,...,...,...,...,...,...,...,...
12277416,2015-06-30 21:20:17,2015-06-30 21:33:33,1,2.05,-73.990448,40.718933,-74.015091,40.715786,14.16
12277774,2015-06-30 21:19:39,2015-06-30 21:39:46,1,4.50,-73.987686,40.760578,-74.014565,40.715675,19.30
12278027,2015-06-30 21:21:42,2015-06-30 21:37:03,2,2.79,-74.011612,40.714249,-74.014267,40.715439,13.30
12278887,2015-06-30 21:20:11,2015-06-30 22:00:25,2,5.90,-73.984200,40.762543,-74.014732,40.714413,32.76
12279480,2015-06-30 21:24:45,2015-06-30 21:42:26,3,4.30,-73.988075,40.756458,-74.014755,40.714199,17.80
12280293,2015-06-30 21:28:30,2015-06-30 21:36:43,2,1.05,-74.002533,40.708698,-74.014572,40.715439,9.96
12280460,2015-06-30 21:23:54,2015-06-30 21:31:54,1,1.77,-73.999306,40.730057,-74.014587,40.715096,11.76
12280572,2015-06-30 21:29:44,2015-06-30 21:43:39,1,4.35,-73.990250,40.718887,-74.015236,40.714100,20.16
12283013,2015-06-30 21:27:37,2015-06-30 21:34:37,1,1.60,-74.003250,40.726986,-74.014931,40.714001,10.55
12283026,2015-06-30 21:27:43,2015-06-30 21:49:25,1,5.30,-73.976776,40.780037,-74.014343,40.715588,21.30
12285140,2015-06-30 22:11:14,2015-06-30 22:21:25,5,2.49,-74.003014,40.744267,-74.015045,40.715660,13.30
12287913,2015-06-30 21:32:00,2015-06-30 21:40:18,1,1.40,-74.004570,40.730618,-74.014893,40.715748,10.30
12288558,2015-06-30 21:50:02,2015-06-30 21:56:23,1,1.45,-74.007660,40.704941,-74.014374,40.715649,9.96
12288696,2015-06-30 22:23:58,2015-06-30 22:41:26,5,3.91,-73.996056,40.759136,-74.015282,40.715649,17.80
12290211,2015-06-30 22:12:54,2015-06-30 22:17:05,2,1.48,-74.004318,40.730824,-74.014999,40.715755,8.76
12291974,2015-06-30 22:26:05,2015-06-30 22:52:15,1,4.91,-73.977386,40.759022,-74.015068,40.715111,21.30
12292263,2015-06-30 22:17:46,2015-06-30 22:25:45,1,1.20,-74.004822,40.721058,-74.014458,40.715416,8.80
12294119,2015-06-30 22:41:37,2015-06-30 22:56:45,1,2.65,-73.985229,40.739014,-74.014519,40.715565,15.96
12295130,2015-06-30 22:43:27,2015-06-30 22:52:02,2,1.58,-74.003479,40.733509,-74.013962,40.715420,11.76
12297626,2015-06-30 22:53:13,2015-06-30 23:04:54,1,2.19,-73.990852,40.734516,-74.014961,40.715595,13.30
12303128,2015-06-30 23:25:49,2015-06-30 23:37:06,5,1.49,-74.004410,40.721638,-74.014526,40.715443,12.10
12303777,2015-06-30 23:34:12,2015-06-30 23:48:43,1,3.11,-73.995064,40.744797,-74.013710,40.714951,16.80
12303819,2015-06-30 20:48:44,2015-06-30 21:16:35,1,7.31,-73.954559,40.763981,-74.013382,40.715092,31.30
12307600,2015-06-30 23:16:11,2015-06-30 23:30:23,1,6.66,-73.967407,40.756222,-74.015121,40.715626,26.16
12309168,2015-06-30 23:21:14,2015-06-30 23:41:38,1,7.15,-73.968895,40.754269,-74.014679,40.715508,29.16
12310170,2015-06-30 23:26:26,2015-06-30 23:38:43,1,2.40,-74.003799,40.742046,-74.014557,40.715408,14.15
12313350,2015-06-30 22:37:20,2015-06-30 23:03:42,1,5.00,-73.980087,40.754871,-74.013779,40.715267,25.07
12319899,2015-06-30 23:39:48,2015-07-01 00:00:43,1,4.56,-73.983261,40.761951,-74.015213,40.715771,24.12
12319984,2015-06-30 23:45:08,2015-06-30 23:51:47,1,1.51,-74.008286,40.705811,-74.014503,40.715393,9.96
12321935,2015-06-30 23:53:20,2015-07-01 00:13:09,1,4.80,-73.979340,40.752525,-74.015259,40.715801,23.15